name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: barberdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./BerberTermine/BerberTermine.sln

      - name: Build solution
        run: dotnet build ./BerberTermine/BerberTermine.sln --configuration Release

      - name: Apply EF Core migrations
        env:
          ConnectionStrings__DefaultConnection: "Server=127.0.0.1;Port=3306;Database=barberdb;User=root;Password=root"
        run: dotnet ef database update --project ./BerberTermine/BerberTermine/BerberTermine.csproj --startup-project ./BerberTermine/BerberTermine/BerberTermine.csproj

      - name: Run tests
        env:
          ConnectionStrings__DefaultConnection: "Server=127.0.0.1;Port=3306;Database=barberdb;User=root;Password=root"
        run: dotnet test ./BerberTermine/BerberTermine.sln --configuration Release --verbosity normal

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'
