name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

     - name: Restore dependencies
      run: dotnet restore ./server/BerberTermine.sln

    - name: Build solution
      run: dotnet build ./server/BerberTermine.sln --no-restore

    - name: Run tests
      run: dotnet test ./server/BerberTermine.sln --no-build --verbosity normal

