name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies (API project)
        run: dotnet restore ./BerberTermine/BerberTermine/BerberTermine.csproj

      - name: Build API project
        run: dotnet build ./BerberTermine/BerberTermine/BerberTermine.csproj --no-restore

      - name: Restore dependencies (Tests project)
        run: dotnet restore ./BerberTermine.Tests/BerberTermine.Tests.csproj

      - name: Build Tests project
        run: dotnet build ./BerberTermine.Tests/BerberTermine.Tests.csproj --no-restore

      - name: Run tests
        run: dotnet test ./BerberTermine.Tests/BerberTermine.Tests.csproj --no-build --verbosity normal
